language: elixir
elixir:
  - 1.5.2
otp_release:
  - 20.1
before_script:
  - nvm install $(cat .nvmrc)
  - nvm use $(cat .nvmrc)
  - yes | mix deps.get
  - yes | mix ecto.create
  - yes | mix ecto.migrate
script:
  - mix test
